version: "3.8"

volumes:
  postgres:

services:
  redis-cache:
    image: redis:5.0
    ports:
      - "6379:6379"

  postgres:
    container_name: local_postgres
    image: "postgres:13"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "p@ssword1!"
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
      - ./db/postgres/postgres_init_database.sql:/docker-entrypoint-initdb.d/postgres_init_database.sql
    ports:
      - "5432:5432"

